[user_samba_share]
   path = /srv/samba/user_share
   comment = Samba share for user

   # access control
   valid users = user
   force user = user
   read only = no
   browseable = yes
   access based share enum = yes

   # permission managemnet
   create mask = 0700
   directory mask = 0700

   # recycle
   vfs objects = recycle
   recycle:repository = .recycle
   recycle:keeptree = yes
   recycle:versions = yes
   recycle:touch = yes
   recycle:maxsize = 0
   recycle:exclude = *.tmp, *.temp, ~$*, .DS_Store
